# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, these are MapStore tasks!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  cloc:
    cmds:
      - |
        cloc --vcs=git --ignored=ignored.txt \
             --force-lang=Mustache,tmpl --force-lang=INI,env --force-lang=INI,dev --force-lang=INI,prod \
             --exclude_ext=yaml,sum,mod,md5 --not-match-f='LICENSE$|\.gitignore$' \
             .

  godepgraph:
    cmds:
      - godepgraph -s -o github.com/ppipada/mapstore-go,command-line-arguments store_directory.go | dot -Tpng -o godepgraph.png

  tagstats:
    cmds:
      - ./scripts/git_tag_stats.sh

  lint-gopls:
    cmds:
      - ./scripts/lint_gopls_check.sh

  lint-godotfix:
    cmds:
      - golangci-lint run --fix --enable-only=godot

  lint-gosort:
    cmds:
      # Use the override of the original refdir at github.com/ppipada/refdir. Do a go get before.
      - refdir ./...

  lint:
    cmds:
      - golangci-lint run ./... -v

  test:
    cmds:
      - go test ./...

  lt:
    cmds:
      - task: lint
      - task: test
